CPM: Readin Class Reference
Readin Class Reference
#include <Readin.h>
Public Slots
void StartReadTxt ()
void StartReadBin ()
Signals
void currentPos (int pos)
void finished ()
Public Member Functions
Readin ()
Readin (QString fName)
~Readin ()
QVector< QVector< quint16 > > GetData ()
Private Attributes
QString m_fileName
QVector< QVector< quint16 > > m_data
Detailed Description
Definition at line 9 of file Readin.h.
Constructor & Destructor Documentation
Readin() [1/2]
Readin::Readin ()
Definition at line 11 of file Readin.cpp.
Readin() [2/2]
Readin::Readin (QString fName)
Definition at line 14 of file Readin.cpp.
References m_fileName.
~Readin()
Readin::~Readin ()
Definition at line 20 of file Readin.cpp.
Member Function Documentation
currentPos
void Readin::currentPos (int pos) signal
finished
void Readin::finished () signal
GetData()
QVector< QVector< quint16 > > Readin::GetData ()
Definition at line 160 of file Readin.cpp.
References m_data.
StartReadBin
void Readin::StartReadBin () slot
Definition at line 74 of file Readin.cpp.
References currentPos(), finished(), m_data, m_fileName, nBK, and nCM.
StartReadTxt
void Readin::StartReadTxt () slot
Definition at line 23 of file Readin.cpp.
References currentPos(), finished(), m_data, and m_fileName.
Member Data Documentation
m_data
QVector< QVector<quint16> > Readin::m_data private
Definition at line 33 of file Readin.h.
m_fileName
QString Readin::m_fileName private
Definition at line 32 of file Readin.h.
The documentation for this class was generated from the following files:
Readin.h
Readin.cpp