CPM: Crystal Class Reference
Crystal Class Reference
#include <Crystal.h>
Public Member Functions
Crystal ()
Crystal (int ID)
~Crystal ()
int GetID ()
void SetID (int ID)
int GetEntries ()
void Fill (quint16 e)
void CalRecEHist ()
Histogram * GetADCHist ()
Histogram * GetRecEHist ()
qreal GetSlope ()
void SetSlope (qreal x)
qreal GetER ()
void Clear ()
Private Attributes
int m_ID
qreal m_slope
QVector< quint16 > m_eList
Histogram * m_ADCHist
Histogram * m_recEHist
Detailed Description
Definition at line 8 of file Crystal.h.
Constructor & Destructor Documentation
Crystal() [1/2]
Crystal::Crystal ()
Definition at line 7 of file Crystal.cpp.
References ADC_max, ADC_min, ADC_nBins, m_ADCHist, m_ID, m_recEHist, m_slope, recE_max, recE_min, and recE_nBins.
Crystal() [2/2]
Crystal::Crystal (int ID)
Definition at line 16 of file Crystal.cpp.
References ADC_max, ADC_min, ADC_nBins, m_ADCHist, m_ID, m_recEHist, m_slope, recE_max, recE_min, and recE_nBins.
~Crystal()
Crystal::~Crystal ()
Definition at line 25 of file Crystal.cpp.
References m_ADCHist, and m_recEHist.
Member Function Documentation
CalRecEHist()
void Crystal::CalRecEHist ()
Definition at line 57 of file Crystal.cpp.
References ADC_cutValue, Histogram::Fill(), Histogram::GetPeak(), m_ADCHist, m_eList, m_recEHist, m_slope, peakE, Histogram::SetCutValue(), and Histogram::Smooth().
Clear()
void Crystal::Clear ()
Definition at line 104 of file Crystal.cpp.
References Histogram::Clear(), m_ADCHist, m_eList, and m_recEHist.
Fill()
void Crystal::Fill (quint16 e)
Definition at line 50 of file Crystal.cpp.
References Histogram::Fill(), m_ADCHist, and m_eList.
GetADCHist()
Histogram * Crystal::GetADCHist ()
Definition at line 78 of file Crystal.cpp.
References m_ADCHist.
GetEntries()
int Crystal::GetEntries ()
Definition at line 44 of file Crystal.cpp.
References m_eList.
GetER()
qreal Crystal::GetER ()
Definition at line 97 of file Crystal.cpp.
References Histogram::GetResolution(), m_recEHist, and Histogram::Smooth().
GetID()
int Crystal::GetID ()
Definition at line 32 of file Crystal.cpp.
References m_ID.
GetRecEHist()
Histogram * Crystal::GetRecEHist ()
Definition at line 72 of file Crystal.cpp.
References m_recEHist.
GetSlope()
qreal Crystal::GetSlope ()
Definition at line 85 of file Crystal.cpp.
References m_slope.
SetID()
void Crystal::SetID (int ID)
Definition at line 38 of file Crystal.cpp.
References m_ID.
SetSlope()
void Crystal::SetSlope (qreal x)
Definition at line 91 of file Crystal.cpp.
References m_slope.
Member Data Documentation
m_ADCHist
Histogram* Crystal::m_ADCHist private
Definition at line 38 of file Crystal.h.
m_eList
QVector<quint16> Crystal::m_eList private
Definition at line 37 of file Crystal.h.
m_ID
int Crystal::m_ID private
Definition at line 35 of file Crystal.h.
m_recEHist
Histogram* Crystal::m_recEHist private
Definition at line 39 of file Crystal.h.
m_slope
qreal Crystal::m_slope private
Definition at line 36 of file Crystal.h.
The documentation for this class was generated from the following files:
Crystal.h
Crystal.cpp