CPM: MainWindow Class Reference
MainWindow Class Reference
#include <MainWindow.h>
Public Member Functions
MainWindow (QWidget *parent=nullptr)
~MainWindow ()
cv::Mat GetColorMap (cv::Mat_< qreal > I)
void ShowImage (cv::Mat_< qreal > I)
void ShowPeaks (cv::Mat_< qreal > I, cv::Mat_< cv::Vec2w > pt)
void ShowADCHist (int peakLoc=-1)
void ShowRecEHist ()
Private Slots
void on_pushButton_readinData_clicked ()
void on_pushButton_setEW_clicked ()
void on_pushButton_segment_clicked ()
void on_pushButton_genPositionLUT_clicked ()
void on_pushButton_genEnergyLUT_clicked ()
void on_pushButton_calPeaks_clicked ()
void on_pushButton_calOnePeak_clicked ()
void on_pushButton_writePeaks_clicked ()
void on_label_eHist_mouseLeftClicked ()
void on_label_eHist_mouseRightClicked ()
void on_label_floodmap_mouseLeftClicked ()
void on_label_floodmap_mouseRightClicked ()
void on_pushButton_calSegFOM_clicked ()
void on_pushButton_calEnergyResolution_clicked ()
void on_pushButton_calUniformity_clicked ()
void on_lineEdit_minEW_editingFinished ()
void on_lineEdit_maxEW_editingFinished ()
void UpdateProgressBar (int pos)
void ReStoreData ()
void on_pushButton_crystalES_clicked ()
Private Attributes
Ui::MainWindow * ui
Readin * dataObject
Block * m_BK
QtCharts::QLineSeries * eHistLine
QtCharts::QLineSeries * EWLeftLine
QtCharts::QLineSeries * EWRightLine
QtCharts::QLineSeries * peakLine
QtCharts::QValueAxis * axisX
QtCharts::QValueAxis * axisY
QtCharts::QChart * chart
QtCharts::QChartView * chartView
qreal m_peakValue = 0
quint8 imgFlag = 0
Detailed Description
Definition at line 23 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr)
Definition at line 18 of file MainWindow.cpp.
References ADC_binWidth, ADC_max, ADC_min, ADC_nBins, axisX, axisY, chart, chartView, eHistLine, EWLeftLine, EWRightLine, m_BK, nPixel, peakLine, ShowImage(), and ui.
~MainWindow()
MainWindow::~MainWindow ()
Definition at line 100 of file MainWindow.cpp.
Member Function Documentation
GetColorMap()
cv::Mat MainWindow::GetColorMap (cv::Mat_< qreal > I)
Definition at line 107 of file MainWindow.cpp.
on_label_eHist_mouseLeftClicked
void MainWindow::on_label_eHist_mouseLeftClicked () private slot
Definition at line 417 of file MainWindow.cpp.
References chart, chartView, EWLeftLine, m_peakValue, and ui.
on_label_eHist_mouseRightClicked
void MainWindow::on_label_eHist_mouseRightClicked () private slot
Definition at line 434 of file MainWindow.cpp.
References chart, chartView, EWRightLine, m_peakValue, and ui.
on_label_floodmap_mouseLeftClicked
void MainWindow::on_label_floodmap_mouseLeftClicked () private slot
Definition at line 451 of file MainWindow.cpp.
References chart, Block::GetCrystal(), Block::GetMap(), Block::GetPeakTable(), imgFlag, m_BK, Block::ManualAdjust(), nCrystal, peakE, Crystal::SetSlope(), ShowADCHist(), ShowPeaks(), and ui.
on_label_floodmap_mouseRightClicked
void MainWindow::on_label_floodmap_mouseRightClicked () private slot
Definition at line 483 of file MainWindow.cpp.
References Block::CalSegResult(), Block::GetSegMap(), imgFlag, m_BK, nCrystal, ShowADCHist(), ShowImage(), ShowRecEHist(), and ui.
on_lineEdit_maxEW_editingFinished
void MainWindow::on_lineEdit_maxEW_editingFinished () private slot
Definition at line 760 of file MainWindow.cpp.
References chartView, EWRightLine, m_peakValue, and ui.
on_lineEdit_minEW_editingFinished
void MainWindow::on_lineEdit_minEW_editingFinished () private slot
Definition at line 749 of file MainWindow.cpp.
References chartView, EWLeftLine, m_peakValue, and ui.
on_pushButton_calEnergyResolution_clicked
void MainWindow::on_pushButton_calEnergyResolution_clicked () private slot
Definition at line 597 of file MainWindow.cpp.
References axisX, axisY, chartView, eHistLine, EWLeftLine, EWRightLine, Histogram::GetBinCenter(), Histogram::GetBinContent(), Block::GetCrystal(), Block::GetER(), Crystal::GetER(), Histogram::GetLeftValue(), Histogram::GetPeak(), Block::GetRecEHist(), Histogram::GetRightValue(), m_BK, nCrystal, nPixel, recE_max, recE_min, recE_nBins, ShowImage(), and ui.
on_pushButton_calOnePeak_clicked
void MainWindow::on_pushButton_calOnePeak_clicked () private slot
Definition at line 379 of file MainWindow.cpp.
References ADC_max, ADC_min, ADC_nBins, axisX, axisY, chartView, eHistLine, EWLeftLine, EWRightLine, Crystal::GetADCHist(), Histogram::GetBinCenter(), Histogram::GetBinContent(), Block::GetCrystal(), Histogram::GetPeak(), imgFlag, m_BK, nCrystal, peakLine, and ui.
on_pushButton_calPeaks_clicked
void MainWindow::on_pushButton_calPeaks_clicked () private slot
Definition at line 329 of file MainWindow.cpp.
References EWLeftLine, EWRightLine, imgFlag, and ShowADCHist().
on_pushButton_calSegFOM_clicked
void MainWindow::on_pushButton_calSegFOM_clicked () private slot
Definition at line 566 of file MainWindow.cpp.
References Block::CalSegFOM(), Block::GetFWHM(), Block::GetPVR(), m_BK, and ui.
on_pushButton_calUniformity_clicked
void MainWindow::on_pushButton_calUniformity_clicked () private slot
Definition at line 690 of file MainWindow.cpp.
References crystalNum, currentPath, fName_LUT_U, Block::GetCrystal(), Crystal::GetEntries(), m_BK, nCrystal, nPixel, ShowImage(), and ui.
on_pushButton_crystalES_clicked
void MainWindow::on_pushButton_crystalES_clicked () private slot
Definition at line 817 of file MainWindow.cpp.
References EWLeftLine, EWRightLine, imgFlag, and ShowRecEHist().
on_pushButton_genEnergyLUT_clicked
void MainWindow::on_pushButton_genEnergyLUT_clicked () private slot
Definition at line 321 of file MainWindow.cpp.
References Block::CalRecEHist(), Block::GenEnergyLUT(), and m_BK.
on_pushButton_genPositionLUT_clicked
void MainWindow::on_pushButton_genPositionLUT_clicked () private slot
Definition at line 314 of file MainWindow.cpp.
References Block::GenPositionLUT(), and m_BK.
on_pushButton_readinData_clicked
void MainWindow::on_pushButton_readinData_clicked () private slot
Definition at line 180 of file MainWindow.cpp.
References dataObject, ReStoreData(), Readin::StartReadTxt(), ui, and UpdateProgressBar().
on_pushButton_segment_clicked
void MainWindow::on_pushButton_segment_clicked () private slot
Definition at line 303 of file MainWindow.cpp.
References Block::GetMap(), Block::GetPeakTable(), imgFlag, m_BK, Block::Segment(), segMethod, ShowPeaks(), and ui.
on_pushButton_setEW_clicked
void MainWindow::on_pushButton_setEW_clicked () private slot
Definition at line 217 of file MainWindow.cpp.
References ADC_cutValue, ADC_max, ADC_min, ADC_nBins, axisX, axisY, Block::CalMap(), chartView, Block::Clear(), currentPath, eHistLine, EW_width, EWLeftLine, EWRightLine, Block::Fill(), Block::GetADCHist(), Histogram::GetBinCenter(), Histogram::GetBinContent(), Block::GetMap(), Histogram::GetPeak(), m_BK, m_peakValue, Histogram::SetCutValue(), ShowImage(), Histogram::Smooth(), ui, xmax, xmin, ymax, and ymin.
on_pushButton_writePeaks_clicked
void MainWindow::on_pushButton_writePeaks_clicked () private slot
Definition at line 576 of file MainWindow.cpp.
References crystalNum, currentPath, fName_LUT_E, Block::GetCrystal(), Crystal::GetSlope(), and m_BK.
ReStoreData
void MainWindow::ReStoreData () private slot
Definition at line 777 of file MainWindow.cpp.
References ADC_max, ADC_min, bias, currentPath, dataObject, enlarge, Readin::GetData(), and nPixel.
ShowADCHist()
void MainWindow::ShowADCHist (int peakLoc = -1)
Definition at line 345 of file MainWindow.cpp.
References ADC_max, ADC_min, ADC_nBins, axisX, axisY, chartView, eHistLine, Crystal::GetADCHist(), Histogram::GetBinCenter(), Histogram::GetBinContent(), Block::GetCrystal(), Histogram::GetPeak(), m_BK, nCrystal, peakLine, and ui.
ShowImage()
void MainWindow::ShowImage (cv::Mat_< qreal > I)
Definition at line 130 of file MainWindow.cpp.
References GetColorMap(), nPixel, and ui.
ShowPeaks()
void MainWindow::ShowPeaks (cv::Mat_< qreal > I, cv::Mat_< cv::Vec2w > pt)
Definition at line 150 of file MainWindow.cpp.
References GetColorMap(), nCrystal, and ui.
ShowRecEHist()
void MainWindow::ShowRecEHist ()
Definition at line 830 of file MainWindow.cpp.
References axisX, axisY, chartView, eHistLine, Histogram::GetBinCenter(), Block::GetCrystal(), Crystal::GetRecEHist(), m_BK, nCrystal, peakLine, recE_max, recE_min, recE_nBins, and ui.
UpdateProgressBar
void MainWindow::UpdateProgressBar (int pos) private slot
Definition at line 771 of file MainWindow.cpp.
References ui.
Member Data Documentation
axisX
QtCharts::QValueAxis* MainWindow::axisX private
Definition at line 80 of file MainWindow.h.
axisY
QtCharts::QValueAxis* MainWindow::axisY private
Definition at line 81 of file MainWindow.h.
chart
QtCharts::QChart* MainWindow::chart private
Definition at line 82 of file MainWindow.h.
chartView
QtCharts::QChartView* MainWindow::chartView private
Definition at line 83 of file MainWindow.h.
dataObject
Readin* MainWindow::dataObject private
Definition at line 71 of file MainWindow.h.
eHistLine
QtCharts::QLineSeries* MainWindow::eHistLine private
Definition at line 76 of file MainWindow.h.
EWLeftLine
QtCharts::QLineSeries* MainWindow::EWLeftLine private
Definition at line 77 of file MainWindow.h.
EWRightLine
QtCharts::QLineSeries* MainWindow::EWRightLine private
Definition at line 78 of file MainWindow.h.
imgFlag
quint8 MainWindow::imgFlag = 0 private
Definition at line 90 of file MainWindow.h.
m_BK
Block* MainWindow::m_BK private
Definition at line 72 of file MainWindow.h.
m_peakValue
qreal MainWindow::m_peakValue = 0 private
Definition at line 85 of file MainWindow.h.
peakLine
QtCharts::QLineSeries* MainWindow::peakLine private
Definition at line 79 of file MainWindow.h.
ui
Ui::MainWindow* MainWindow::ui private
Definition at line 69 of file MainWindow.h.
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp