CPM: Block Class Reference
Block Class Reference
#include <Block.h>
Public Member Functions
Block ()
Block (int ID)
~Block ()
int GetID ()
void SetID (int ID)
void Fill (quint16 x, quint16 y, quint16 e)
void CalMap (int EW_min, int EW_max)
void Segment (SegmentMethod method)
void Segment1 ()
void Segment2 ()
void ManualAdjust (QPoint pos)
void CalSegResult ()
void CalRecEHist ()
void CalSegFOM ()
void GenPositionLUT ()
void GenEnergyLUT ()
void GenUniformityLUT ()
Crystal * GetCrystal (int ID)
Histogram * GetADCHist ()
Histogram * GetRecEHist ()
cv::Mat_< qreal > GetMap ()
cv::Mat_< cv::Vec2w > GetPeakTable ()
cv::Mat_< quint16 > GetSegResult ()
cv::Mat_< qreal > GetSegMap ()
qreal GetER ()
qreal GetPVR ()
qreal GetFWHM ()
qreal CalFWHM (cv::Mat I)
void Clear ()
Private Member Functions
void CalGroupPar ()
QVector< int > FindPeaks (QVector< qreal > v, int nPeaks)
Private Attributes
int m_ID
QVector< quint16 > m_xList
QVector< quint16 > m_yList
QVector< quint16 > m_eList
QVector< Crystal * > m_crystals
Histogram * m_ADCHist
Histogram * m_recEHist
cv::Mat_< qreal > m_I0
cv::Mat_< quint16 > m_segr
cv::Mat_< quint8 > m_edge
cv::Mat_< qreal > m_segMap
cv::Mat_< cv::Vec2w > m_pt
int m_num1
int m_num2
qreal m_PVR
qreal m_FWHM
Detailed Description
Definition at line 10 of file Block.h.
Constructor & Destructor Documentation
Block() [1/2]
Block::Block ()
Definition at line 12 of file Block.cpp.
References ADC_max, ADC_min, ADC_nBins, CalGroupPar(), crystalNum, m_ADCHist, m_crystals, m_edge, m_FWHM, m_I0, m_ID, m_pt, m_PVR, m_recEHist, m_segMap, m_segr, nCrystal, nPixel, recE_max, recE_min, and recE_nBins.
Block() [2/2]
Block::Block (int ID)
Definition at line 39 of file Block.cpp.
References ADC_max, ADC_min, ADC_nBins, CalGroupPar(), crystalNum, m_ADCHist, m_crystals, m_edge, m_FWHM, m_I0, m_ID, m_pt, m_PVR, m_recEHist, m_segMap, m_segr, nCrystal, nPixel, recE_max, recE_min, and recE_nBins.
~Block()
Block::~Block ()
Definition at line 66 of file Block.cpp.
References m_ADCHist, m_crystals, and m_recEHist.
Member Function Documentation
CalFWHM()
qreal Block::CalFWHM (cv::Mat I)
Definition at line 719 of file Block.cpp.
CalGroupPar()
void Block::CalGroupPar () private
Definition at line 778 of file Block.cpp.
References m_num1, m_num2, and nCrystal.
CalMap()
void Block::CalMap (int EW_min, int EW_max)
Definition at line 99 of file Block.cpp.
References m_eList, m_I0, m_xList, and m_yList.
CalRecEHist()
void Block::CalRecEHist ()
Definition at line 460 of file Block.cpp.
References Histogram::Add(), m_crystals, m_eList, m_recEHist, m_segr, m_xList, m_yList, and recE_cutValue.
CalSegFOM()
void Block::CalSegFOM ()
Definition at line 483 of file Block.cpp.
References CalFWHM(), crystalNum, m_edge, m_FWHM, m_I0, m_pt, m_PVR, nCrystal, nPixel, xmax, xmin, ymax, and ymin.
CalSegResult()
void Block::CalSegResult ()
Definition at line 395 of file Block.cpp.
References m_edge, m_I0, m_pt, m_segMap, m_segr, nCrystal, and nPixel.
Clear()
void Block::Clear ()
Definition at line 756 of file Block.cpp.
References Histogram::Clear(), m_ADCHist, m_crystals, m_edge, m_eList, m_I0, m_pt, m_recEHist, m_segMap, m_segr, m_xList, and m_yList.
Fill()
void Block::Fill (quint16 x, quint16 y, quint16 e)
Definition at line 90 of file Block.cpp.
References Histogram::Fill(), m_ADCHist, m_eList, m_xList, and m_yList.
FindPeaks()
QVector< int > Block::FindPeaks (QVector< qreal > v, int nPeaks) private
Definition at line 811 of file Block.cpp.
References nPixel.
GenEnergyLUT()
void Block::GenEnergyLUT ()
Definition at line 629 of file Block.cpp.
References crystalNum, currentPath, fName_LUT_E, and m_crystals.
GenPositionLUT()
void Block::GenPositionLUT ()
Definition at line 542 of file Block.cpp.
References currentPath, fName_LUT_P, m_segr, nCrystal, and nPixel.
GenUniformityLUT()
void Block::GenUniformityLUT ()
Definition at line 650 of file Block.cpp.
GetADCHist()
Histogram * Block::GetADCHist ()
Definition at line 669 of file Block.cpp.
References m_ADCHist.
GetCrystal()
Crystal * Block::GetCrystal (int ID)
Definition at line 663 of file Block.cpp.
References m_crystals.
GetER()
qreal Block::GetER ()
Definition at line 699 of file Block.cpp.
References Histogram::GetResolution(), m_recEHist, recE_cutValue, Histogram::SetCutValue(), and Histogram::Smooth().
GetFWHM()
qreal Block::GetFWHM ()
Definition at line 713 of file Block.cpp.
References m_FWHM.
GetID()
int Block::GetID ()
Definition at line 78 of file Block.cpp.
References m_ID.
GetMap()
cv::Mat_< qreal > Block::GetMap ()
Definition at line 657 of file Block.cpp.
References m_I0.
GetPeakTable()
cv::Mat_< cv::Vec2w > Block::GetPeakTable ()
Definition at line 681 of file Block.cpp.
References m_pt.
GetPVR()
qreal Block::GetPVR ()
Definition at line 707 of file Block.cpp.
References m_PVR.
GetRecEHist()
Histogram * Block::GetRecEHist ()
Definition at line 675 of file Block.cpp.
References m_recEHist.
GetSegMap()
cv::Mat_< qreal > Block::GetSegMap ()
Definition at line 693 of file Block.cpp.
References m_segMap.
GetSegResult()
cv::Mat_< quint16 > Block::GetSegResult ()
Definition at line 687 of file Block.cpp.
References m_segr.
ManualAdjust()
void Block::ManualAdjust (QPoint pos)
Definition at line 374 of file Block.cpp.
References m_pt, and nCrystal.
Segment()
void Block::Segment (SegmentMethod method)
Definition at line 116 of file Block.cpp.
References FindMaximum, Segment1(), Segment2(), and SVD.
Segment1()
void Block::Segment1 ()
Definition at line 133 of file Block.cpp.
References FindPeaks(), m_I0, m_num1, m_num2, m_pt, nCrystal, and nPixel.
Segment2()
void Block::Segment2 ()
Definition at line 316 of file Block.cpp.
References crystalNum, m_I0, m_pt, and nCrystal.
SetID()
void Block::SetID (int ID)
Definition at line 84 of file Block.cpp.
References m_ID.
Member Data Documentation
m_ADCHist
Histogram* Block::m_ADCHist private
Definition at line 65 of file Block.h.
m_crystals
QVector<Crystal*> Block::m_crystals private
Definition at line 63 of file Block.h.
m_edge
cv::Mat_<quint8> Block::m_edge private
Definition at line 70 of file Block.h.
m_eList
QVector<quint16> Block::m_eList private
Definition at line 61 of file Block.h.
m_FWHM
qreal Block::m_FWHM private
Definition at line 79 of file Block.h.
m_I0
cv::Mat_<qreal> Block::m_I0 private
Definition at line 68 of file Block.h.
m_ID
int Block::m_ID private
Definition at line 57 of file Block.h.
m_num1
int Block::m_num1 private
Definition at line 75 of file Block.h.
m_num2
int Block::m_num2 private
Definition at line 76 of file Block.h.
m_pt
cv::Mat_<cv::Vec2w> Block::m_pt private
Definition at line 73 of file Block.h.
m_PVR
qreal Block::m_PVR private
Definition at line 78 of file Block.h.
m_recEHist
Histogram* Block::m_recEHist private
Definition at line 66 of file Block.h.
m_segMap
cv::Mat_<qreal> Block::m_segMap private
Definition at line 71 of file Block.h.
m_segr
cv::Mat_<quint16> Block::m_segr private
Definition at line 69 of file Block.h.
m_xList
QVector<quint16> Block::m_xList private
Definition at line 59 of file Block.h.
m_yList
QVector<quint16> Block::m_yList private
Definition at line 60 of file Block.h.
The documentation for this class was generated from the following files:
Block.h
Block.cpp